# Private email gateway

version: '2'

services:
  getmail_dovecot:
    #build: http://github.com/zoot1612/docker-dovecot-getmail.git
    image: zoot1612/dovecot-getmail:latest
    volumes:
      - /docker/containers/dovecot-getmail/home:/home
      - /docker/containers/dovecot-getmail/etc/cron.d:/etc/cron.d
      - /docker/containers/dovecot-getmail/etc/ssl/private:/etc/ssl/private:ro
    ports:
      - "143:143"  # imap
      - "993:993"  # imaps
      - "4190:4190"  # managesieve
    restart: unless-stopped
